[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simo-sonos"
version = "1.2.17"
authors = [
  { name="Simon V.", email="simon@simo.io" },
]
description = "SONOS integration for SIMO.io"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/SIMO-io/simo-sonos"
Issues = "https://github.com/SIMO-io/simo-sonos/issues"
